name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is wrong?
      placeholder: Clear and short problem description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste errors or screenshots if available
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: Windows version, Python version, browser
